name: CI - Validation and Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate HTML, CSS, and JS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g html-validate stylelint eslint
          
      - name: Validate HTML
        run: |
          # Basic HTML validation
          echo "Validating HTML files..."
          for file in *.html; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              # Check for basic HTML structure
              if ! grep -q "<!DOCTYPE html>" "$file"; then
                echo "Warning: $file missing DOCTYPE declaration"
              fi
              if ! grep -q "<html" "$file"; then
                echo "Error: $file missing html tag"
                exit 1
              fi
              if ! grep -q "<head>" "$file"; then
                echo "Error: $file missing head tag"
                exit 1
              fi
              if ! grep -q "<body>" "$file"; then
                echo "Error: $file missing body tag"
                exit 1
              fi
            fi
          done
          echo "HTML validation completed"
          
      - name: Validate CSS
        run: |
          echo "Validating CSS files..."
          for file in *.css; do
            if [ -f "$file" ]; then
              echo "Checking $file for syntax..."
              # Basic CSS syntax check
              if ! node -e "
                const fs = require('fs');
                const css = fs.readFileSync('$file', 'utf8');
                // Basic check for unmatched braces
                const openBraces = (css.match(/{/g) || []).length;
                const closeBraces = (css.match(/}/g) || []).length;
                if (openBraces !== closeBraces) {
                  console.error('Unmatched braces in $file');
                  process.exit(1);
                }
                console.log('$file: Braces match (' + openBraces + ' pairs)');
              "; then
                echo "CSS validation failed for $file"
                exit 1
              fi
            fi
          done
          echo "CSS validation completed"
          
      - name: Validate JavaScript
        run: |
          echo "Validating JavaScript files..."
          for file in *.js; do
            if [ -f "$file" ]; then
              echo "Checking $file for syntax..."
              if ! node -c "$file"; then
                echo "JavaScript syntax error in $file"
                exit 1
              fi
            fi
          done
          echo "JavaScript validation completed"
          
      - name: Check file structure
        run: |
          echo "Checking required files..."
          required_files=("index.html" "styles.css" "script.js")
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file is missing"
              exit 1
            else
              echo "✓ $file exists"
            fi
          done
          
      - name: Check links and references
        run: |
          echo "Checking internal file references..."
          # Check if CSS and JS files are properly referenced in HTML
          if ! grep -q "styles.css" index.html; then
            echo "Warning: styles.css not found in index.html"
          fi
          if ! grep -q "script.js" index.html; then
            echo "Warning: script.js not found in index.html"
          fi
          echo "Link validation completed"
          
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse CI
    needs: validate
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
        
      - name: Serve site locally
        run: |
          # Start a simple HTTP server
          python3 -m http.server 8080 &
          sleep 5
          
      - name: Run Lighthouse CI
        run: |
          lhci autorun || echo "Lighthouse completed with warnings"
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
          LHCI_BUILD_CONTEXT__COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
          
  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Scan for secrets
        run: |
          echo "Scanning for potential secrets..."
          # Basic secret scanning
          if grep -r -i "api_key\|secret\|password\|token" . --exclude-dir=.git; then
            echo "Warning: Potential secrets found - please review"
          else
            echo "No obvious secrets detected"
          fi
          
      - name: Check for security headers
        run: |
          echo "Checking for security best practices..."
          if grep -q "Content-Security-Policy" *.html; then
            echo "✓ CSP headers found"
          else
            echo "ℹ️ Consider adding Content-Security-Policy headers"
          fi